### ISSUE TITLE
SQLiteException when importing .ics file

### ISSUE THREAD

**Issue by jojbak** [SimpleMobileTools/Simple-Calendar#446]
Hi,
I get an SQLiteException when importing contents of an .ics file, none of the events are successfully imported to the app. I sucessfully validated the file at https://icalendar.org/validator.html so I don't believe that the file is the problem. At first I suspected it had to do with the file containing nordic characters but since I could import the Swedish holidays file without problems I guess the cause is something else? Therefore I'm not really sure where to start since the file seems alright.

Contents of the .ics file: https://pastebin.com/hW4amdyt
Thanks in advance

**Comment by tibbi** [comment]
Hey, what is written in the error message? Can you attach a screenshot or type it out? Thanks

**Comment by jojbak** [comment]
First I get the error message:
"an error occured:
android.database.sqlite.SQLiteException"
Followed by:
"Importing some events failed"

**Comment by jojbak** [comment]
Checked the system logs and these are the exceptions thrown in Android, I'm running Nougat so below are the related classes. Probably doesn't say much so I'll continue by trying to debugging the app in Android Studio when I get the time.

E DatabaseUtils: Writing exception to parcel
E DatabaseUtils: android.database.sqlite.SQLiteDoneException
E DatabaseUtils:         at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
E DatabaseUtils:         at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:598)
E DatabaseUtils:         at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
E DatabaseUtils:         at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
E DatabaseUtils:         at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:845)
E DatabaseUtils:         at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:833)
E DatabaseUtils:         at com.android.providers.calendar.CalendarDatabaseHelper.duplicateEvent(CalendarDatabaseHelper.java:3371)
E DatabaseUtils:         at com.android.providers.calendar.CalendarProvider2.insertInTransaction(CalendarProvider2.java:2323)
E DatabaseUtils:         at com.android.providers.calendar.SQLiteContentProvider.insert(SQLiteContentProvider.java:100)
E DatabaseUtils:         at android.content.ContentProvider$Transport.insert(ContentProvider.java:264)
E DatabaseUtils:         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:163)
E DatabaseUtils:         at android.os.Binder.execTransact(Binder.java:565)

https://android.googlesource.com/platform/frameworks/base/+/nougat-release/core/java/android/database/sqlite/SQLiteConnection.java
https://android.googlesource.com/platform/frameworks/base/+/nougat-release/core/java/android/database/DatabaseUtils.java
https://android.googlesource.com/platform/packages/providers/CalendarProvider/+/nougat-release/src/com/android/providers/calendar/CalendarDatabaseHelper.java
https://android.googlesource.com/platform/packages/providers/CalendarProvider/+/nougat-release/src/com/android/providers/calendar/CalendarProvider2.java
